# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and source code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Ensure MasterMCP.py is executable
RUN chmod +x MasterMCP.py

# Set environment variables if any
# Default command
CMD ["python", "MasterMCP.py"]
